name: Lint and test

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ⬇️
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          submodules: recursive

      - name: Setup python 🐍
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install dependencies ☕️
        run: |
          source setup.sh ""

      - name: Lint 🔍
        run: |
          source setup.sh ""
          ./tests/run_linting

  lint_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ⬇️
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          submodules: recursive

      - name: Setup python 🐍
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install dependencies ☕️
        run: |
          source setup.sh ""

      - name: Lint 🔍
        run: |
          source setup.sh ""
          ./tests/run_docs lint || true

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ⬇️
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          submodules: recursive

      - name: Setup python 🐍
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install dependencies ☕️
        run: |
          source setup.sh ""

      - name: Test 🎢
        run: |
          source setup.sh ""
          ./tests/run_tests

  pypi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ⬇️
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          submodules: recursive

      - name: Setup python 🐍
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install dependencies ☕️
        run: |
          pip install -U pip
          pip install twine

      - name: Check bundling 📦
        run: python setup.py sdist

      - name: Check setup 🚦
        run: twine check "dist/$( python setup.py --fullname ).tar.gz"

  coverage:
    runs-on: ubuntu-latest
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    steps:
      - name: Checkout ⬇️
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          submodules: recursive

      - name: Setup python 🐍
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install dependencies ☕️
        run: |
          source setup.sh ""

      - name: Run coverage test 🎢
        run: |
          source setup.sh ""
          ./tests/run_coverage
          ls -al

      - name: Upload report 🔝
        uses: codecov/codecov-action@v4
        with:
          flags: unittests
          files: coverage_test_util.xml,coverage_test_columnar_util.xml
          verbose: true
